desc "Building your App in version beta"
lane :beta do |options|
  puts "+---------------------------------+".bold.blue
  puts "|-- Environment: #{options[:env]} 🚀 --|".bold.blue
  puts "+---------------------------------+".bold.blue

  increment_version_code(
    gradle_file_path: "app/build.gradle",
  )
  gradle(
    task: "clean assembleRelease",
    properties: {
      "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
      "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
    }
  )
  firebase_app_distribution(
    app: ENV['APP_ID'],
    groups: ENV["GROUPS"] || options[:groups],
    release_notes: options[:notes] ||  ENV['RELEASE_NOTE'],
  )
end